### PR TITLE
send metrics for specific message instead of last send

### PR DESCRIPTION
**Pull request by edewit**

### CODE REVIEW

**Comment by matzew** [comment]
should this be merged ? any JIRA reference ?

**Comment by edewit** [comment]
you could have multiple messages as windows stacks them in the notification tray, this will give you the ability to send metrics for a specific message instead of the last one send.

**Comment by matzew** [comment]
Looks like needs a rebase. any JIRA ticket for this ?

**Comment by edewit** [comment]
no jira issue for this just a quick fix when testing the HelloWorld

**Comment by edewit** [comment]
opened new PR that is rebased https://github.com/aerogear/aerogear-windows-push/pull/13

**Pull request closed without merging**
