### PR TITLE
fix for renewed id

### PR DESCRIPTION
**Pull request by edewit**
fixing issue [AGCORDOVA-53](https://issues.jboss.org/browse/AGCORDOVA-53)

### CODE REVIEW

**Comment by matzew** [comment]
@edewit please add folks for review, that way is easier to track why something was not merged.

**Comment by matzew** [comment]
@lfryc @sebastienblanc can you review ?

**Comment by secondsun** [comment]
How do I test this? (IE what is the bug being fixed, what behavior should I see, what prerequisites do I need to run it)

**Comment by edewit** [comment]
[AGCORDOVA-53](https://issues.jboss.org/browse/AGCORDOVA-53) is the issue that is solved

**Comment by secondsun** [comment]
@edewit That doesn't help me understand though.  I know nothing about Windows other than open in Visual studio and hit compile.  Can you answer my questions with that as a frame of reference?

**Comment by edewit** [comment]
So windows will hand you a ChannelUri when you register a device for push notifications and will continue to use that same ChannelUri. When the ChannelUri is changed the windows lib would not reflect that change back to UPS this fix fixes that.

**Comment by secondsun** [comment]
@edewit How does the channelUri get changed?

**Comment by edewit** [comment]
@secondsun not sure when that happens, the logic is on MS side, but it can. And when it happens UPS should know about it

**Comment by sebastienblanc** [comment]
:+1: 
@secondsun Are you still testing this or can it be merged ?

**Comment by secondsun** [comment]
@sebastienblanc Merge it.

**Pull request merged**
